// frontend/components/turnstile-widget.tsx
"use client"

import { forwardRef, useEffect, useImperativeHandle, useRef } from "react"

type TurnstileApi = {
  render: (element: HTMLElement, options: Record<string, unknown>) => string
  reset: (widgetId?: string) => void
  remove: (widgetId: string) => void
}

declare global {
  interface Window {
    turnstile?: TurnstileApi
  }
}

export type TurnstileWidgetHandle = { reset: () => void }

type TurnstileWidgetProps = {
  siteKey: string
  action: "login" | "register"
  onVerified: (token: string) => void
  onExpired: () => void
  onError: () => void
}

function loadTurnstileScript() {
  return new Promise<void>((resolve, reject) => {
    if (window.turnstile) return resolve()
    const existing = document.querySelector<HTMLScriptElement>("script[data-turnstile-script]")
    if (existing) {
      existing.addEventListener("load", () => resolve(), { once: true })
      existing.addEventListener("error", () => reject(new Error("Turnstile script failed")), { once: true })
      return
    }

    const script = document.createElement("script")
    script.src = "https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit"
    script.async = true
    script.defer = true
    script.dataset.turnstileScript = "true"
    script.onload = () => resolve()
    script.onerror = () => reject(new Error("Turnstile script failed"))
    document.head.appendChild(script)
  })
}

export const TurnstileWidget = forwardRef<TurnstileWidgetHandle, TurnstileWidgetProps>(function TurnstileWidget({ siteKey, action, onVerified, onExpired, onError }, ref) {
  const containerRef = useRef<HTMLDivElement>(null)
  const widgetIdRef = useRef("")

  useImperativeHandle(ref, () => ({
    reset: () => {
      if (widgetIdRef.current && window.turnstile) window.turnstile.reset(widgetIdRef.current)
    },
  }), [])

  useEffect(() => {
    let active = true

    async function renderWidget() {
      if (!siteKey || !containerRef.current) return
      try {
        await loadTurnstileScript()
        if (!active || !window.turnstile || !containerRef.current) return
        if (widgetIdRef.current) window.turnstile.remove(widgetIdRef.current)
        widgetIdRef.current = window.turnstile.render(containerRef.current, {
          sitekey: siteKey,
          action,
          theme: "light",
          size: "flexible",
          callback: onVerified,
          "expired-callback": onExpired,
          "error-callback": onError,
        })
      } catch {
        if (active) onError()
      }
    }

    void renderWidget()
    return () => {
      active = false
      if (widgetIdRef.current && window.turnstile) window.turnstile.remove(widgetIdRef.current)
      widgetIdRef.current = ""
    }
  }, [action, onError, onExpired, onVerified, siteKey])

  return <div ref={containerRef} className="grid min-h-16 w-full place-items-center" aria-label="人机验证" />
})

// frontend/src/components/TurnstileWidget.vue
<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue";

type TurnstileAPI = {
  render: (element: HTMLElement, options: Record<string, unknown>) => string;
  reset: (widgetId?: string) => void;
  remove: (widgetId: string) => void;
};

declare global {
  interface Window {
    turnstile?: TurnstileAPI;
  }
}

const props = defineProps<{
  siteKey: string;
  action: "login" | "register";
}>();

const emit = defineEmits<{
  verified: [token: string];
  expired: [];
  error: [];
}>();

const container = ref<HTMLElement | null>(null);
let widgetID = "";

function loadScript() {
  return new Promise<void>((resolve, reject) => {
    if (window.turnstile) {
      resolve();
      return;
    }

    const existing = document.querySelector<HTMLScriptElement>("script[data-turnstile-script]");
    if (existing) {
      existing.addEventListener("load", () => resolve(), { once: true });
      existing.addEventListener("error", () => reject(new Error("Turnstile script failed")), { once: true });
      return;
    }

    const script = document.createElement("script");
    script.src = "https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit";
    script.async = true;
    script.defer = true;
    script.dataset.turnstileScript = "true";
    script.onload = () => resolve();
    script.onerror = () => reject(new Error("Turnstile script failed"));
    document.head.appendChild(script);
  });
}

async function renderWidget() {
  if (!props.siteKey || !container.value) return;
  await loadScript();
  await nextTick();
  if (!window.turnstile || !container.value) return;

  if (widgetID) {
    window.turnstile.remove(widgetID);
    widgetID = "";
  }
  widgetID = window.turnstile.render(container.value, {
    sitekey: props.siteKey,
    action: props.action,
    theme: "dark",
    size: "flexible",
    callback: (token: string) => emit("verified", token),
    "expired-callback": () => emit("expired"),
    "error-callback": () => emit("error"),
  });
}

function reset() {
  if (widgetID && window.turnstile) {
    window.turnstile.reset(widgetID);
  }
}

defineExpose({ reset });

onMounted(() => {
  void renderWidget();
});

watch(
  () => props.action,
  () => {
    void renderWidget();
  },
);

onBeforeUnmount(() => {
  if (widgetID && window.turnstile) {
    window.turnstile.remove(widgetID);
  }
});
</script>

<template>
  <div ref="container" class="turnstile-widget" />
</template>

<style scoped>
.turnstile-widget {
  min-height: 65px;
  width: 100%;
  display: grid;
  place-items: center;
}
</style>
