// frontend/src/components/MetricCard.vue
<script setup lang="ts">
import type { Component } from "vue";

withDefaults(defineProps<{
  label: string;
  value: string | number;
  detail?: string;
  tone?: "neutral" | "green" | "amber" | "red" | "blue";
  icon: Component;
}>(), {
  detail: "",
  tone: "neutral"
});
</script>

<template>
  <article :class="['metric-panel', `metric-panel--${tone}`]">
    <div class="flex items-start justify-between gap-3">
      <div>
        <p class="text-sm font-medium text-muted-foreground">{{ label }}</p>
        <p class="mt-3 font-mono text-3xl font-bold tracking-[-0.05em] tabular-nums lg:text-4xl">{{ value }}</p>
      </div>
      <span class="metric-icon" aria-hidden="true">
        <component :is="icon" />
      </span>
    </div>
    <p v-if="detail" class="mt-4 text-xs leading-5 text-muted-foreground">{{ detail }}</p>
  </article>
</template>

// frontend/components/metric-card.tsx
import type { LucideIcon } from "lucide-react"

import { Card, CardContent } from "@/components/ui/card"

export function MetricCard({ compact = false, label, value, detail, icon: Icon }: { compact?: boolean; label: string; value: number; detail: string; icon: LucideIcon }) {
  const summary = <div aria-label={`${label} 指标`} className={`flex items-start justify-between gap-3 ${compact ? "p-3" : "p-4"}`}><div><p className="text-sm text-muted-foreground">{label}</p><p className={`font-semibold tabular-nums ${compact ? "mt-1 text-xl" : "mt-2 text-2xl"}`}>{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><span className="rounded-lg bg-muted p-2 text-muted-foreground"><Icon className="size-4" /></span></div>

  if (compact) return summary

  return <Card className="shadow-none" data-testid="metric-card"><CardContent className="p-0">{summary}</CardContent></Card>
}
