// frontend/src/components/YybLoginDialog.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { CheckCircle2, Link2Off, Loader2, QrCode, RefreshCw, ShieldCheck } from "@lucide/vue";
import { createDiscreteApi } from "naive-ui";
import { Button as UiButton } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger
} from "@/components/ui/dialog";
import CookieDialog from "@/components/CookieDialog.vue";
import { useYYBStore } from "@/stores/yyb";

const yyb = useYYBStore();
const { message } = createDiscreteApi(["message"]);
const open = ref(false);
const advanced = ref(false);

const qrImage = computed(() => yyb.qr?.imageBase64 || "");
const pollStatusMessage = computed(() => {
  switch (yyb.poll?.status) {
    case "pending":
      return "等待扫码，请使用微信扫描左侧二维码。";
    case "scanned":
      return "已扫码，请在微信中确认登录。";
    case "authorized":
    case "confirmed":
      return "扫码已确认，可以点击确认绑定。";
    case "expired":
      return "二维码已过期，请重新生成。";
    case "cancelled":
      return "扫码已取消，请重新生成二维码。";
    case "unknown":
      return "扫码状态暂时无法识别，请稍后再检查。";
    default:
      return "";
  }
});
const statusText = computed(() => {
  if (yyb.binding.bound) {
    const name = yyb.binding.nickname || "微信账号";
    return `${name} 已绑定${yyb.binding.openidSuffix ? `（尾号 ${yyb.binding.openidSuffix}）` : ""}`;
  }
  if (yyb.poll?.message) return yyb.poll.message;
  if (pollStatusMessage.value) return pollStatusMessage.value;
  if (yyb.qr) return "请使用微信扫码，扫码完成后点击确认。";
  return "生成二维码后，扫码结果会通过 Charge 后端确认并保存到当前账户。";
});
const confirmDisabled = computed(() => !yyb.qr?.sessionId || yyb.confirming);

async function loadBinding() {
  try {
    await yyb.fetchBinding();
  } catch (error) {
    message.error((error as Error).message);
  }
}

async function createQR() {
  try {
    await yyb.createQR();
    message.success("二维码已生成，扫码后请点击检查扫码状态");
  } catch (error) {
    message.error((error as Error).message);
  }
}

async function pollOnce() {
  try {
    await yyb.pollQR();
    message.success(statusText.value || "扫码状态已更新");
  } catch (error) {
    message.error((error as Error).message);
  }
}

async function confirmQR() {
  try {
    const result = await yyb.confirmQR();
    message.success(result.message || (result.cookieSynced ? "扫码登录已生效" : "扫码登录已完成"));
  } catch (error) {
    message.error((error as Error).message);
  }
}

async function clearBinding() {
  try {
    await yyb.clearBinding();
    message.success("扫码绑定已解除");
  } catch (error) {
    message.error((error as Error).message);
  }
}

watch(open, (value) => {
  if (value) {
    void loadBinding();
  }
});
</script>

<template>
  <Dialog v-model:open="open">
    <DialogTrigger as-child>
      <UiButton class="dashboard-action" variant="outline"><QrCode />扫码登录</UiButton>
    </DialogTrigger>
    <DialogContent data-testid="yyb-login-dialog" class="max-h-[calc(100dvh-2rem)] overflow-y-auto sm:max-w-2xl">
      <DialogHeader>
        <DialogTitle class="flex items-center gap-2"><ShieldCheck class="size-5 text-primary" />扫码登录远端账号</DialogTitle>
        <DialogDescription>
          微信扫码后，Charge 会通过后端服务保存当前账户的登录绑定；以后添加充电桩时会自动维护访问凭据。
        </DialogDescription>
      </DialogHeader>

      <div class="yyb-login-grid">
        <section class="yyb-qr-panel" aria-label="扫码二维码">
          <div v-if="qrImage" class="yyb-qr-frame">
            <img :src="qrImage" alt="微信扫码登录二维码">
          </div>
          <div v-else class="yyb-qr-placeholder">
            <QrCode class="size-10" />
            <p>二维码尚未生成</p>
          </div>
          <UiButton class="mt-4 w-full" :disabled="yyb.loading" @click="createQR">
            <Loader2 v-if="yyb.loading" class="animate-spin" />
            <QrCode v-else />
            {{ yyb.loading ? "生成中…" : "生成扫码二维码" }}
          </UiButton>
        </section>

        <section class="yyb-status-panel" aria-live="polite">
          <div :class="['yyb-binding-card', yyb.binding.bound ? 'yyb-binding-card--active' : '']">
            <CheckCircle2 v-if="yyb.binding.bound" class="size-5 text-primary" />
            <ShieldCheck v-else class="size-5 text-muted-foreground" />
            <div>
              <strong>{{ yyb.binding.bound ? "已绑定扫码登录" : "尚未绑定" }}</strong>
              <p>{{ statusText }}</p>
            </div>
          </div>

          <div class="grid gap-2 sm:grid-cols-2">
            <UiButton variant="outline" :disabled="!yyb.qr || yyb.polling" @click="pollOnce">
              <Loader2 v-if="yyb.polling" class="animate-spin" />
              <RefreshCw v-else />
              检查扫码状态
            </UiButton>
            <UiButton :disabled="confirmDisabled" @click="confirmQR">
              <Loader2 v-if="yyb.confirming" class="animate-spin" />
              <CheckCircle2 v-else />
              确认绑定
            </UiButton>
          </div>

          <p class="rounded-xl bg-secondary/60 p-3 text-xs leading-5 text-muted-foreground">
            如果当前账户已经添加过充电桩，确认绑定后会立即尝试同步凭据；如果还没有设备，后续通过“添加充电桩”入口添加时会自动生效。
          </p>

          <button class="advanced-toggle" type="button" @click="advanced = !advanced">
            {{ advanced ? "收起高级设置" : "高级设置：手动 Cookie 与解绑" }}
          </button>
          <div v-if="advanced" class="grid gap-2 rounded-xl border border-border bg-background/60 p-3">
            <CookieDialog trigger-label="手动更新 Cookie" trigger-class="w-full justify-start" />
            <UiButton variant="destructive" class="justify-start" :disabled="!yyb.binding.bound" @click="clearBinding">
              <Link2Off />解除扫码绑定
            </UiButton>
          </div>
        </section>
      </div>

      <DialogFooter class="sticky bottom-0 -mx-6 -mb-6 mt-2 border-t border-border bg-background/95 px-6 py-4 backdrop-blur supports-[backdrop-filter]:bg-background/80 sm:static sm:m-0 sm:border-0 sm:bg-transparent sm:p-0 sm:backdrop-blur-none">
        <UiButton data-testid="yyb-login-close" variant="ghost" @click="open = false">关闭</UiButton>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

// frontend/components/yyb-login-dialog.tsx
"use client"

import { CheckCircle2Icon, Link2OffIcon, LoaderCircleIcon, QrCodeIcon, RefreshCwIcon, ShieldCheckIcon } from "lucide-react"
import { useEffect, useState } from "react"
import { toast } from "sonner"

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { useDashboard } from "@/lib/dashboard-context"
import { requestEmpty, requestJSON } from "@/lib/http"

type Binding = { bound: boolean; openidSuffix?: string; nickname?: string; message?: string; cookieSynced?: boolean }
type QR = { sessionId: string; imageUrl?: string; imageBase64?: string }
type Poll = { sessionId: string; status: string; message?: string }

export function YybLoginDialog() {
  const { updateCookie } = useDashboard()
  const [open, setOpen] = useState(false)
  const [advanced, setAdvanced] = useState(false)
  const [binding, setBinding] = useState<Binding>({ bound: false })
  const [qr, setQr] = useState<QR | null>(null)
  const [poll, setPoll] = useState<Poll | null>(null)
  const [loading, setLoading] = useState(false)
  const [polling, setPolling] = useState(false)
  const [confirming, setConfirming] = useState(false)
  const [cookie, setCookie] = useState("")

  useEffect(() => { if (open) void requestJSON<Binding>("/api/session/yyb-binding", {}, "暂时无法读取扫码绑定状态，请稍后重试。").then(setBinding).catch((reason) => toast.error(reason.message)) }, [open])
  const status = binding.bound ? `${binding.nickname || "微信账号"} 已绑定${binding.openidSuffix ? `（尾号 ${binding.openidSuffix}）` : ""}` : poll?.message || ({ pending: "等待扫码，请使用微信扫描左侧二维码。", scanned: "已扫码，请在微信中确认登录。", authorized: "扫码已确认，可以点击确认绑定。", confirmed: "扫码已确认，可以点击确认绑定。", expired: "二维码已过期，请重新生成。", cancelled: "扫码已取消，请重新生成二维码。" }[poll?.status ?? ""] || (qr ? "请使用微信扫码，扫码完成后点击确认。" : "生成二维码后，扫码结果会通过 Charge 后端确认并保存到当前账户。"))

  async function createQr() { setLoading(true); try { const next = await requestJSON<QR>("/api/session/yyb-qr", { method: "POST" }, "二维码暂时无法生成，请稍后重试。"); setQr(next); setPoll(null); toast.success("二维码已生成，扫码后请点击检查扫码状态") } catch (reason) { toast.error((reason as Error).message) } finally { setLoading(false) } }
  async function checkStatus() { if (!qr) return; setPolling(true); try { const next = await requestJSON<Poll>(`/api/session/yyb-qr/${encodeURIComponent(qr.sessionId)}/poll`, {}, "暂时无法获取扫码状态，请稍后重试。"); setPoll(next); toast.success(next.message || "扫码状态已更新") } catch (reason) { toast.error((reason as Error).message) } finally { setPolling(false) } }
  async function confirm() { if (!qr) return; setConfirming(true); try { const next = await requestJSON<Binding>(`/api/session/yyb-qr/${encodeURIComponent(qr.sessionId)}/confirm`, { method: "POST" }, "暂时无法确认扫码结果，请稍后重试。"); setBinding(next); setQr(null); setPoll(null); toast.success(next.message || (next.cookieSynced ? "扫码登录已生效" : "扫码登录已完成")) } catch (reason) { toast.error((reason as Error).message) } finally { setConfirming(false) } }
  async function clearBinding() { try { await requestEmpty("/api/session/yyb-binding", { method: "DELETE" }, "解除扫码绑定失败，请稍后重试。"); setBinding({ bound: false }); setQr(null); setPoll(null); toast.success("扫码绑定已解除") } catch (reason) { toast.error((reason as Error).message) } }
  async function saveCookie(event: React.FormEvent) { event.preventDefault(); try { await updateCookie(cookie); setCookie(""); toast.success("Cookie 已更新") } catch (reason) { toast.error((reason as Error).message) } }

  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button variant="outline"><QrCodeIcon />扫码登录</Button>} /><DialogContent className="max-h-[calc(100dvh-2rem)] w-[min(48rem,calc(100%-2rem))] max-w-none overflow-y-auto sm:max-w-none"><DialogHeader><DialogTitle className="flex items-center gap-2"><ShieldCheckIcon className="size-5" />扫码登录远端账号</DialogTitle><DialogDescription>微信扫码后会保存当前账户的登录绑定；以后添加充电桩时会自动维护访问凭据。</DialogDescription></DialogHeader><Alert><ShieldCheckIcon /><AlertTitle>手机端使用提醒</AlertTitle><AlertDescription>二维码仅支持微信扫一扫摄像头识别，不能通过截图、长按图片或相册读取。手机端请在另一台设备打开本页面，再用当前手机微信扫码。</AlertDescription></Alert><div className="grid gap-5 sm:grid-cols-2"><section className="rounded-lg border bg-muted/30 p-4 text-center">{qr?.imageBase64 || qr?.imageUrl ? <img src={qr.imageBase64 || qr.imageUrl} alt="微信扫码登录二维码" className="mx-auto aspect-square w-full max-w-56 rounded bg-white p-2" /> : <div className="grid aspect-square w-full place-items-center text-muted-foreground"><div><QrCodeIcon className="mx-auto size-10" /><p className="mt-2 text-sm">二维码尚未生成</p></div></div>}<Button className="mt-4 w-full" disabled={loading} onClick={() => void createQr()}>{loading ? <LoaderCircleIcon className="animate-spin" /> : <QrCodeIcon />}{loading ? "生成中…" : "生成扫码二维码"}</Button></section><section className="space-y-3"><CardStatus bound={binding.bound} status={status} /><div className="grid gap-2"><Button variant="outline" disabled={!qr || polling} onClick={() => void checkStatus()}>{polling ? <LoaderCircleIcon className="animate-spin" /> : <RefreshCwIcon />}检查扫码状态</Button><Button disabled={!qr || confirming} onClick={() => void confirm()}>{confirming ? <LoaderCircleIcon className="animate-spin" /> : <CheckCircle2Icon />}确认绑定</Button></div><p className="rounded-lg bg-muted p-3 text-xs leading-5 text-muted-foreground">确认绑定后会立即尝试同步凭据；如果还没有设备，后续通过“添加充电桩”入口添加时会自动生效。</p><Button variant="ghost" className="px-0" onClick={() => setAdvanced((value) => !value)}>{advanced ? "收起高级设置" : "高级设置：手动 Cookie 与解绑"}</Button>{advanced && <div className="space-y-3 rounded-lg border p-3"><form onSubmit={saveCookie}><FieldGroup><Field><FieldLabel htmlFor="manual-cookie">手动更新 Cookie</FieldLabel><Input id="manual-cookie" value={cookie} onChange={(event) => setCookie(event.target.value)} placeholder="粘贴 Cookie" /></Field><Button className="w-full" type="submit">更新 Cookie</Button></FieldGroup></form><Button variant="destructive" className="w-full" disabled={!binding.bound} onClick={() => void clearBinding()}><Link2OffIcon />解除扫码绑定</Button></div>}</section></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>关闭</Button></DialogFooter></DialogContent></Dialog>
}

function CardStatus({ bound, status }: { bound: boolean; status: string }) { return <div className="rounded-lg border p-3"><div className="flex gap-2"><>{bound ? <CheckCircle2Icon className="mt-0.5 size-5" /> : <ShieldCheckIcon className="mt-0.5 size-5 text-muted-foreground" />}</><div><p className="text-sm font-semibold">{bound ? "已绑定扫码登录" : "尚未绑定"}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{status}</p></div></div></div> }
